name: goxlr_bridge
description: Expose GoXLR's Streamdeck api as REST endpoints
version: 1.0.0

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  dart_amqp: ^0.2.1
  shelf_router: ^1.1.2
  websocket: ^0.0.5
  logging: ^1.0.2 
  args: ^2.3.0
